export default {
  updateInterval: 2000,
  account: null,
  balance: null,
  network: null,
  unlocked: null,
  rpcUrl: null,
  blockNumber: null,
  gasPrice: null,
  fallbackHost: 'http://127.0.0.1:8545',
  connected: null,
  isInjected: null,
  provider: null,
  metamaskDisabled: false,
};
